function sep_setup_paths()
%SEP_SETUP_PATHS  Put the project's code on the MATLAB path.
%   SEP_SETUP_PATHS() runs once per session, before any driver. A check starts
%   from a fresh session, so nothing an earlier run put on the path can shadow
%   the code under test:
%
%     restoredefaultpath; cd('D:\sep_histology\code'); sep_setup_paths
%
%   It adds an explicit list of our code folders, and the vendored toolboxes
%   in third_party\ (LightSuite, yamlmatlab, matlab_elastix, Bio-Formats) with
%   their subfolders. The order on the path, from the top: our folders, then
%   the toolboxes, then MATLAB's own functions: LightSuite above MATLAB's
%   functions is the precedence every result so far was produced with.
%   tests\sep_test_path checks that no function name is defined twice on this
%   path.
%
%   Never added: the code root with its subfolders (genpath), archive\,
%   tests\, tools\ (a check adds it by hand, see tools\README.md), mapping\
%   (Python), the Python engines' folders, and any data or atlas folder.
%   get_atlas adds the one atlas folder a run needs: LightSuite finds the
%   atlas with which(), so a second atlas folder on the path would be picked
%   up silently.
%
%   Refuses to run when a file the refactor moved out of the code root is back
%   there under its old name: an editor tab left open on the old file and
%   saved again recreates it, and the old copy would then run, or shadow the
%   moved one.

code_dir = fileparts(mfilename('fullpath'));

% the .m files moved out of the code root in step 4 of docs/REFACTOR_PLAN.md
% (docs/refactor_name_map.csv says where each one went)
moved = { ...
    'P0_copy_raw_data.m', 'P1_extract_and_center_data.m', 'P1bis_order_slices.m', ...
    'P2_residual_correction_analysis.m', 'P2bis_nano_correction_analysis.m', ...
    'P3_annotate_artifacts.m', 'P4_register_to_atlas.m', 'P4bis_add_sep_channel.m', ...
    'P5_collect_data_by_group.m', 'P6bis_analyze_group_averages_and_normalize.m', ...
    'P7bis_analyze_group_differences.m', ...
    'make_ordering_volume.m', 'make_atlas_reference_sheet.m', 'ArtifactAnnotator.m', ...
    'select_reference_pixels.m', 'remap_control_points.m', 'auto_annotate.m', ...
    'recompute_backvalues.m', 'check_registration_error.m', 'verify_demba_setup.m', ...
    'get_atlas.m', 'get_atlas_crop.m', 'cohort_atlas_key.m', 'get_allen_region_mask.m', ...
    'atlas_diagnostics.m', 'check_demba_to_allen.m', 'compare_atlas_regions.m', ...
    'compare_atlases_montage.m', 'get_cohort.m', 'get_cohort_spec.m', 'loadVolume.m', ...
    'compute_lr_stats.m', 'get_color2color_colormap.m', 'select_background_pixels.m', ...
    'write_lr_indiv_rolling_video.m', 'write_lr_indiv_video.m', ...
    'write_lr_indiv_video_signed.m', 'write_lr_video.m', 'write_lr_video_surpmask.m', ...
    'write_lr_video_surpmask_rolling.m', 'test_backward_compat.m', ...
    'P6_analyze_group_averages_and_normalize.m', 'P7_analyze_group_differences.m', ...
    'plot_abs_slice.m', 'plot_diff_slice.m', 'write_diff_video.m', 'lr_sum_and_diff.m', ...
    'scratch.m'};
back = moved(cellfun(@(f) isfile(fullfile(code_dir, f)), moved));
if ~isempty(back)
    error(['sep_setup_paths: %s is back at the code root (%s) under its name from ' ...
           'before the refactor, which moved it (docs/refactor_name_map.csv). An ' ...
           'editor tab saved after the move recreates it. Carry any edit over to the ' ...
           'moved file, then delete the old one.'], strjoin(back, ', '), code_dir);
end

% the vendored toolboxes first, with their subfolders, so that our folders,
% added after them, end up above them
toolboxes = {'LightSuite', 'yamlmatlab', 'matlab_elastix', 'BioformatsImage'};
for k = 1:numel(toolboxes)
    addpath(genpath(fullfile(code_dir, 'third_party', toolboxes{k})));
end

% our folders, one by one: a new folder is added to this list by hand
folders = {'', 'common', 'atlas', fullfile('atlas', 'qc'), 'preprocessing', ...
    fullfile('preprocessing', 'pipeline'), 'registration', ...
    fullfile('registration', 'pipeline'), fullfile('registration', 'qc'), ...
    fullfile('registration', 'annotation_gui'), ...
    'group_comparison', fullfile('group_comparison', 'pipeline')};
folders = cellfun(@(f) fullfile(code_dir, f), folders, 'UniformOutput', false);
addpath(folders{:});

end
